### ISSUE TITLE
Verbosity on failing dataset ingestion

### ISSUE THREAD

**Issue by linupi** [SciCatProject/scicat-backend-next#150]
## Verbosity of failing dataset ingestion

When testing the new backend we ( @linupi and @AnastasiiaSereda ) saw that there are some minor changes in the _requiered_  entries in what is requested by _POST api/v3/datasets_ . If dataset ingestion fails on a missing required or wrongly formatted field the new backend replies simply with STATUS 500 __internal server errror__. Here is an example in Postman with missing _principalInvestigator_:

![grafik](https://user-images.githubusercontent.com/3169764/189609511-d3978bbd-e637-4168-8ac0-2f38e8f60d8d.png)

However, looking at the backend process there is useful information that could be redirected into the response of the failing request in some way. Here is an example:

![grafik](https://user-images.githubusercontent.com/3169764/189609924-2bbf42f9-505e-4ab1-be09-516bb2866550.png)

So instead of just receiving an _internal server errror_ it would be nice to actually get the message that the _principalInvestigator_ was missing in the request and that this is the reason why it could not be processed.

**Comment by linupi** [comment]
Acutally there is a simmiar problem with the _MeasurementPeriodList_ as part of the Proposal metadata. It took us a while to identify that this field is now mandatory. I am not sure how swagger generates the examples given in _explorer-next_ but obviously there are mandatory fiels missing in the given templates.

**Comment by nitrosx** [comment]
@linupi: while working on the tests, I'm also implementing the data validation. 
With the new data validation, the issue that you mention in this issue, should be solved.
You can check the code in the following branch https://github.com/SciCatProject/scicat-backend-next/tree/SWAP-2755

**Comment by linupi** [comment]
@nitrosx :  @AnastasiiaSereda tested on [SWAP-2755](https://github.com/SciCatProject/scicat-backend-next/tree/SWAP-2755), but actually the problem remains the same: There is no feedback to the user through the response of the backend, but just an internal server error.
In above's example we e.g. expect the _principalInvestigator requiered_ message from NESTJS to be exposed through the backend in the response.

**Comment by nitrosx** [comment]
@linupi my apologies. I did not commit the latest changes. I just did that. Now it should validate datasets correctly. It is a work-in progress on the samples.
